on: [push]
name: CI
jobs:
  build_and_test:
    name: "build & test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets
        env:
          SQLX_OFFLINE: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          SQLX_OFFLINE: true
