on: [push]

name: CI

jobs:
  build_and_test:
    name: "build & test"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[rust]')"
    steps:
      - uses: actions/checkout@v3

      - name: Setup TypeScript compiler
        run: yarn global add typescript@next

      - name: Install build dependencies
        run: sudo apt-get install -y -q sassc
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Setup Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
        env:
          SQLX_OFFLINE: true

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          SQLX_OFFLINE: true

  check-js:
    name: "check frontend code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: cd ircj-serve && yarn

      - name: Run ESLint
        run: cd ircj-serve && ./node_modules/.bin/eslint . --ext .ts
