on: [push]

name: CI

jobs:
  build_and_test:
    name: "build & test"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[rust]')"
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: cargo build
        run: nix build

      - name: cargo test
        run: nix develop --command cargo test 

  check-js:
    name: "check frontend code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd ircj-serve && yarn

      - name: Run ESLint
        run: cd ircj-serve && ./node_modules/.bin/eslint . --ext .ts
