on: [push]
name: CI
jobs:
  build_and_test:
    name: "build & test"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')"
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets
        env:
          SQLX_OFFLINE: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          SQLX_OFFLINE: true

  clippy:
    name: "check code with clippy and tslint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: tslint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: "ircj-serve/tslint.json"
          pattern: "ircj-serve/static/js/*.ts"
