on: [push]
name: CI
jobs:
  build_and_test:
    name: "build & test"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[rust]')"
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets
        env:
          SQLX_OFFLINE: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          SQLX_OFFLINE: true

  check-rust:
    name: "check rust code"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[rust]')"
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  check-js:
    name: "check frontend code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: cd ircj-serve && yarn

      - name: Run ESLint
        run: cd ircj-serve && ./node_modules/.bin/eslint . --ext .ts
