on: [push]
name: CI
jobs:
  build_and_test:
    name: "build & test"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[rust]')"
    steps:
      - uses: actions/checkout@v2

      - name: Setup TypeScript compiler
        run: yarn global add typescript@next

      - name: Setup dart-sass
        env:
          DART_VERSION: 1.42.1
        run: |
          wget "https://github.com/sass/dart-sass/releases/download/${DART_VERSION}/dart-sass-${DART_VERSION}-linux-x64.tar.gz" -O dart.tar.gz
          tar xzf dart.tar.gz dart-sass/sass
          echo "$(realpath ./dart-sass)" >> $GITHUB_PATH

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
        env:
          SQLX_OFFLINE: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          SQLX_OFFLINE: true

      - name: clippy
        uses: actions-rs/clippy-check@v1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  check-js:
    name: "check frontend code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: cd ircj-serve && yarn

      - name: Run ESLint
        run: cd ircj-serve && ./node_modules/.bin/eslint . --ext .ts
